### ISSUE TITLE
Error from v0.15.18

### ISSUE THREAD

**Issue by Tomirad** [FKuerten/factorio-tree-growth-natural-growth#3]
![image](https://cloud.githubusercontent.com/assets/12190843/26755362/b0d2beba-488b-11e7-8f4e-7ba8f5acc2d9.png)

**Comment by FKuerten** [comment]
That does not tell me much, except maybe that you are using an outdated version. Try updating to 2.0.1.
In any case I need more details, at least the list of mods you use and ideally a short description what you did when this happened.

**Comment by Tomirad** [comment]
khm..  I check mod and see this content. Sorry for trouble :)

![image](https://user-images.githubusercontent.com/12190843/27000966-19d91a62-4dbe-11e7-8599-77d18e380a93.png)
